import { motion } from "motion/react";
import { ArrowLeft } from "lucide-react";
import { Button } from "./ui/button";
import { BrandLogo } from "./BrandLogo";

interface PrivacyPolicyProps {
  onNavigate: (screen: string) => void;
}

export function PrivacyPolicy({ onNavigate }: PrivacyPolicyProps) {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border bg-card/30 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => onNavigate('landing')}
                className="flex items-center space-x-2 text-muted-foreground hover:text-foreground"
              >
                <ArrowLeft className="h-4 w-4" />
                <span>Back to Home</span>
              </Button>
            </div>
            <BrandLogo />
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold">Privacy Policy</h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              This Privacy Policy describes how BrandSense collects, uses, and protects your information when you use our service.
            </p>
            <p className="text-sm text-muted-foreground">
              Last updated: January 8, 2025
            </p>
          </div>

          {/* Privacy Content */}
          <div className="prose prose-lg max-w-none space-y-8">
            
            {/* 1. Information We Collect */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                1. Information We Collect
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.
                </p>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Personal Information</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Name and email address</li>
                  <li>Company and position information</li>
                  <li>Workspace name and preferences</li>
                  <li>Account credentials and authentication data</li>
                </ul>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Brand Data</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Brand names and descriptions you provide</li>
                  <li>Analysis results and insights generated by our AI</li>
                  <li>Project data and configurations</li>
                  <li>Usage patterns and preferences</li>
                </ul>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Technical Information</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>IP address and device information</li>
                  <li>Browser type and version</li>
                  <li>Usage logs and analytics data</li>
                  <li>Cookies and similar tracking technologies</li>
                </ul>
              </div>
            </section>

            {/* 2. How We Use Your Information */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                2. How We Use Your Information
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>We use the information we collect to:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Provide, maintain, and improve our services</li>
                  <li>Process your brand analysis requests using AI technology</li>
                  <li>Generate insights and reports for your brand monitoring</li>
                  <li>Communicate with you about your account and our services</li>
                  <li>Send you technical notices, updates, and support messages</li>
                  <li>Respond to your comments, questions, and requests</li>
                  <li>Monitor and analyze usage patterns and trends</li>
                  <li>Detect, prevent, and address technical issues and security threats</li>
                </ul>
              </div>
            </section>

            {/* 3. Information Sharing */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                3. Information Sharing and Disclosure
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>We do not sell, trade, or otherwise transfer your personal information to third parties, except in the following circumstances:</p>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Workspace Sharing</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>If you invite another user to your workspace, they will have access to shared project data</li>
                  <li>Both users in a workspace can view and modify shared projects</li>
                  <li>Workspace members can see each other's activity within the shared workspace</li>
                </ul>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Service Providers</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>We may share information with trusted service providers who assist us in operating our platform</li>
                  <li>These providers are bound by confidentiality agreements and are prohibited from using your information for other purposes</li>
                </ul>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Legal Requirements</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>We may disclose information if required by law or to protect our rights and safety</li>
                  <li>We may share information in connection with a business transfer or acquisition</li>
                </ul>
              </div>
            </section>

            {/* 4. Data Security */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                4. Data Security
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Encryption of data in transit and at rest</li>
                  <li>Regular security assessments and updates</li>
                  <li>Access controls and authentication mechanisms</li>
                  <li>Secure data centers and infrastructure</li>
                  <li>Employee training on data protection practices</li>
                </ul>
                <p>
                  However, no method of transmission over the internet or electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee absolute security.
                </p>
              </div>
            </section>

            {/* 5. Data Retention */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                5. Data Retention
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  We retain your information for as long as necessary to provide our services and fulfill the purposes outlined in this Privacy Policy.
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Account information is retained while your account is active</li>
                  <li>Project data is retained until you delete it or close your account</li>
                  <li>Analytics and usage data may be retained for up to 2 years for service improvement</li>
                  <li>Legal and regulatory requirements may require longer retention periods</li>
                </ul>
                <p>
                  When you delete your account, we will delete your personal information within 30 days, except where we are required to retain it for legal or regulatory purposes.
                </p>
              </div>
            </section>

            {/* 6. Your Rights */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                6. Your Rights and Choices
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>You have the following rights regarding your personal information:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li><strong>Access:</strong> Request a copy of the personal information we hold about you</li>
                  <li><strong>Correction:</strong> Request correction of inaccurate or incomplete information</li>
                  <li><strong>Deletion:</strong> Request deletion of your personal information</li>
                  <li><strong>Portability:</strong> Request transfer of your data to another service</li>
                  <li><strong>Restriction:</strong> Request limitation of processing of your information</li>
                  <li><strong>Objection:</strong> Object to processing of your information for certain purposes</li>
                </ul>
                <p>
                  To exercise these rights, please contact us at omerlhn@gmail.com. We will respond to your request within 30 days.
                </p>
              </div>
            </section>

            {/* 7. Cookies and Tracking */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                7. Cookies and Tracking Technologies
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  We use cookies and similar tracking technologies to enhance your experience and analyze usage patterns.
                </p>
                <h3 className="text-lg font-medium text-foreground mt-6 mb-3">Types of Cookies</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li><strong>Essential Cookies:</strong> Required for basic website functionality</li>
                  <li><strong>Analytics Cookies:</strong> Help us understand how you use our service</li>
                  <li><strong>Preference Cookies:</strong> Remember your settings and preferences</li>
                </ul>
                <p>
                  You can control cookie settings through your browser preferences. However, disabling certain cookies may affect the functionality of our service.
                </p>
              </div>
            </section>

            {/* 8. Third-Party Services */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                8. Third-Party Services
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  Our service integrates with third-party services to provide functionality:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li><strong>OpenAI:</strong> For AI-powered brand analysis and insights</li>
                  <li><strong>Supabase:</strong> For database and authentication services</li>
                  <li><strong>Resend:</strong> For email communication services</li>
                </ul>
                <p>
                  These third-party services have their own privacy policies. We encourage you to review their privacy practices before using our service.
                </p>
              </div>
            </section>

            {/* 9. International Transfers */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                9. International Data Transfers
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your information during such transfers.
                </p>
                <p>
                  By using our service, you consent to the transfer of your information to countries that may have different data protection laws than your country of residence.
                </p>
              </div>
            </section>

            {/* 10. Children's Privacy */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                10. Children's Privacy
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  Our service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13.
                </p>
                <p>
                  If you are a parent or guardian and believe your child has provided us with personal information, please contact us immediately.
                </p>
              </div>
            </section>

            {/* 11. Changes to Privacy Policy */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">
                11. Changes to This Privacy Policy
              </h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  We may update this Privacy Policy from time to time. We will notify you of any material changes by email or through our service.
                </p>
                <p>
                  Your continued use of our service after such changes constitutes acceptance of the updated Privacy Policy.
                </p>
              </div>
            </section>

            {/* 12. Contact Information */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Contact Information</h2>
              <div className="space-y-4 text-muted-foreground">
                <p>
                  If you have any questions about this Privacy Policy or our data practices, please contact us:
                </p>
                <div className="bg-card p-6 rounded-lg border">
                  <p><strong>Email:</strong> omerlhn@gmail.com</p>
                  <p><strong>Website:</strong> https://brandsense.digital</p>
                  <p><strong>Support:</strong> Available through the in-app support system</p>
                </div>
              </div>
            </section>

          </div>

          {/* Footer Actions */}
          <div className="flex justify-center pt-8 border-t">
            <Button 
              onClick={() => onNavigate('landing')}
              variant="outline"
              className="px-8"
            >
              Back to Home
            </Button>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
